export const CHANGE_GITLAB_USERNAME = "CHANGE_GITLAB_USERNAME";
export const INIT_CONFIG = "INIT_CONFIG";
export const LOGOUT = "LOGOUT";

/* Reports */
export const CREATE_DAILY = "CREATE_DAILY";
export const ADD_CREATED_ISSUE = "ADD_CREATED_ISSUE";
export const REMOVE_CREATED_ISSUE = "REMOVE_CREATED_ISSUE";
export const ADD_DEVELOPED_ISSUE = "ADD_DEVELOPED_ISSUE";
export const REMOVE_DEVELOPED_ISSUE = "REMOVE_DEVELOPED_ISSUE";
export const ADD_TESTED = "ADD_TESTED";
export const REMOVE_TESTED = "REMOVE_TESTED";
export const CLOSE_NEW_REPORT = "CLOSE_NEW_REPORT";
